- server.js
Minor change for test pull request
> Change Port Listen Text

- models/order.js
> testing branch connection

- src/scss/styles.scss
Compiled colors from me and San
> Add Basic Whole App Styling

- src/pages/FAQPage/FAQDropdown.js
- src/pages/FAQPage/FAQDropdown.module.scss
- src/pages/FAQPage/FAQPage.js
- src/pages/FAQPage/FAQPage.module.scss
Created the FAQ page 8/29/2023
> FAQ Page Created

- src/components/HamMenu/HamMenu.js
- src/components/HamMenu/HamMenu.module.scss
Ignore previous pull request. I forgot to add something to it
> Add Styles and Functionality to Hamburger Menu

- src/pages/UserProfilePage/UserProfilePage.js
- src/pages/UserProfilePage/UserProfilePage.module.scss
> User profile page

- src/pages/AuthPage/AuthPage.js
- src/pages/AuthPage/AuthPage.module.scss
Created the Authentication Page
> Created the Auth page

- src/components/SignUpForm/SignUpForm.js
- src/components/SignUpForm/SignUpForm.module.scss
> Created the signup form

- src/components/LoginForm/LoginForm.js
- src/components/LoginForm/LoginForm.module.scss
> Created the login form

- src/components/UserLogOut/UserLogOut.js
- src/components/UserLogOut/UserLogOut.module.scss
Created the user logout component.
> User Logout Component

- src/components/DeleteUser/DeleteUser.js
- src/components/DeleteUser/DeleteUser.module.scss
Created the delete user component.
> Delete User Component

- README.md
Created a draft of the README.
> README Draft

- src/components/DeleteUser/DeleteUser.js
- src/utilities/users-service.js
Added a delete user function to the users-service.js file. The DeleteUser.js component requires this.
> Added a delete user function to users-service.js

- src/scss/styles.scss
Just changed the comment format from // to /* */
> Change Comment Format in styles.scss File

- src/components/DynamicStars/DynamicStars.js
- src/components/Review/Review.js
- src/components/Review/Review.module.scss
The import file for DynamicStars.js should have reflected './DynamicStars.module.scss' not './DynamicStar.module.scss'.
> Created the Review component and fixed DynamicStars.js scss import file!

- controllers/api/categories.js
- controllers/api/departments.js
- controllers/api/items.js
- controllers/api/users.js
changed from exports.functionName to module.exports = {...} format.
> changed format of module exports

- src/pages/CategoryListPage/CategoryListPage.js
Just made minor change so this is the correct pull request
> Category list page

- package-lock.json
- package.json
Run npm i after this update. The package.json is updated with test dependancies.
> Tests json

- config/seed.js
organized the seed file added more items
> updated seed file

- controllers/api/categories.js
- public/index.html
fixed category controller and now my get category by department route is working
> updated controller categories

- public/css/styles.css
- src/pages/UserProfilePage/UserProfilePage.js
> userprofile

- config/seed.js
last commit didnt add the bottom half of the image changes
> last commit

- src/components/DepListNavBar/DepListNavBar.js
- src/components/DepartmentList/DepartmentList.js
- src/components/NavBar/NavBar.js
- src/components/NavBar/NavBar.module.scss
- src/utilities/catDep-api.js
- src/utilities/items-api.js
> Home Page all links, navbar all links work and all links can navigate from one another

- models/user.js
from firstName /lastName to name
> renamed the user

- controllers/api/wishlist.js
- public/index.html
- routes/api/wishlist.js
removed routes from wishlist that we are not using and those functions in the wishlist controller as well
> removed routes from wishlist that we are not using

- README.md
this is just a readme update with deployed link
> added deployed version

- README.md
erd image got a 404 error reposted it, it works for me
> fixing ERD pic

- README.md
> hopefully fixes erd

- README.md
best I could do was have the link to the image
> imgur link
